CELL_SIZE = 100
EMPTY_TOKEN = '.'

COLOR_WHITE = 'w'
COLOR_BLACK = 'b'

PIECE_KING = 'K'
PIECE_QUEEN = 'Q'
PIECE_ROOK = 'R'
PIECE_BISHOP = 'B'
PIECE_KNIGHT = 'N'
PIECE_PAWN = 'P'

VALID_COLORS = {COLOR_WHITE, COLOR_BLACK}
VALID_PIECES = {PIECE_KING, PIECE_QUEEN, PIECE_ROOK, PIECE_BISHOP, PIECE_KNIGHT, PIECE_PAWN}
DURATION = 1000
COOLDOWN_DURATION = 1000
COOLDOWN_JUMP = 500
COOLDOWN_MOVE = 1500
TOKEN_LENGTH = 2
COLOR_INDEX = 0
KIND_INDEX = 1

PAWN_DIRECTION_WHITE = -1
PAWN_DIRECTION_BLACK = 1
PAWN_DIRECTIONS = {
    COLOR_WHITE: PAWN_DIRECTION_WHITE,
    COLOR_BLACK: PAWN_DIRECTION_BLACK,
}