CELL_SIZE = 100
EMPTY_TOKEN = '.'

COLOR_WHITE = 'w'
COLOR_BLACK = 'b'

PIECE_KING = 'K'
PIECE_QUEEN = 'Q'
PIECE_ROOK = 'R'
PIECE_BISHOP = 'B'
PIECE_KNIGHT = 'N'
PIECE_PAWN = 'P'

VALID_COLORS = {COLOR_WHITE, COLOR_BLACK}
VALID_PIECES = {PIECE_KING, PIECE_QUEEN, PIECE_ROOK, PIECE_BISHOP, PIECE_KNIGHT, PIECE_PAWN}
DURATION = 1000
COOLDOWN_DURATION = 1000
TOKEN_LENGTH = 2
COLOR_INDEX = 0
KIND_INDEX = 1